"""new fields in user mode

Revision ID: 28211ae365da
Revises: 110266bf2069
Create Date: 2020-11-02 10:54:57.538530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28211ae365da'
down_revision = '110266bf2069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
